### ISSUE TITLE
puzzle about running enviroment

### ISSUE THREAD

**Issue by mituanzi** [embedded-sec/uRAI#2]
Hello, I would like to ask, in what environment does this project need to be successfully compiled and run？

**Comment by nalmakhd** [comment]
Hi @mituanzi ,

This was built using the following:
- Ubuntu 14.04 (It should not matter if you are using an newer release)
- LLVM 7.0.1
- arm-none-eabi-gcc 7.3.1

To build the project:
-  Make sure you have all the pre-requisites shown in the README.
-  Follow the instructions shown in the README (from Setup and afterwards). The instructions there are detailed to which instructions you should run.

Please be aware that the scripts take a while to complete. They will not only compile LLVM, but also compile arm-none-eabi-gcc from source...etc. 

Let us know if you have any other questions.

**Comment by mituanzi** [comment]
Hi, @nalmakhd ,

Your answer helps me a lot, thank you very much for your meticulousness and patience.

**Comment by mituanzi** [comment]
Hi, @nalmakhd ,

I ran into a problem when running the following command：

```
python {REPO_ROOT}/compiler/tools/built_tools/CubeMX2Makefile.py . <path to repo root> <Name of the app (e.g., FatFs_RAMDisk) >
```
![image](https://user-images.githubusercontent.com/43168673/104862638-86562800-596e-11eb-9981-a949bf8afe0d.png)

Does this project lack such a file? 

Thank you a lot.

mituanzi

**Comment by nalmakhd** [comment]
Hi @mituanzi ,

You are correct. That file was missing. I just added it so please pull the repository again.

Thanks for pointing this out!

**Comment by mituanzi** [comment]
Thanks(*^▽^*), nalmakhd
