### ISSUE TITLE
cannot find gcc-arm-none-eabi-6-2018-q4-major

### ISSUE THREAD

**Issue by zhangjuxtu** [embedded-sec/uRAI#3]
Hi, I want to setup the project according to the instruction fo README.md. 
After  executing the command "./setup_scripts/init_project.sh", I got the following error:
mv: cannot stat 'gcc-arm-none-eabi-6-2018-q4-major': No such file or directory

I check the directory of ${PROJECT_ROOT_DIR}/gcc/gcc-arm-none-eabi-6-2017-q1-update/pkg, it is empty.
Where is 'gcc-arm-none-eabi-6-2018-q4-major'?
Could you please help me to fix this problem?

Regards,
Jun

**Comment by nalmakhd** [comment]
Hi @zhangjuxtu ,

Thanks for your comment. I am testing the build process again to see if I can replicate what you have. Until then, could you help me with the following?


1. Have you installed all the pre-requisites on the README?
2. Do you see the folder `${PROJECT_ROOT_DIR}/compiler/3rd_party`? Could you list what is inside that folder? If you see nothing, please skip to 4.
3. Could please list the content of `${PROJECT_ROOT_DIR}/gcc/gcc-arm-none-eabi-6-2017-q1-update`? Seems to me there is a problem with building gcc from source. 
4. Could you pull the repository again and check if things work? (Apparently there was a missing folder, which might have been the issue)

**Comment by nalmakhd** [comment]
Hi @zhangjuxtu ,

I tried the installation script and the main issue was the `gcc-arm-none-eab` folder was updated to the 2021 version, namely `gcc-arm-none-eabi-6-2021-q1-update`. I updated the `init_project.sh` script and it should work fine now.

What I mean is that `${PROJECT_ROOT_DIR}/gcc/gcc-arm-none-eabi-6-2017-q1-update/pkg` should not be empty, but rather the issues I found were in following commands (https://github.com/embedded-sec/uRAI/blob/master/compiler/setup_scripts/init_project.sh#L81-L83) where the version changed so these commands did not work. 

Could you verify that you installed the pre-requisites, then pull the repository again and try the installation again. Hopefully it should work this time.

Thanks

**Comment by zhangjuxtu** [comment]
Thanks for your response. Currently, I had installed pre-requisites and pulled the new repository. After running the "init_project.sh" script, it reported the following error:
~/workspace/uRAI/gcc/gcc-arm-none-eabi-6-2017-q1-update/src
mv: target '../../bins/' is not a directory
Should I build the 'bins' directory under '~/workspace/uRAI/gcc/'?

**Comment by zhangjuxtu** [comment]
> Hi @zhangjuxtu ,
> 
> I tried the installation script and the main issue was the `gcc-arm-none-eab` folder was updated to the 2021 version, namely `gcc-arm-none-eabi-6-2021-q1-update`. I updated the `init_project.sh` script and it should work fine now.
> 
> What I mean is that `${PROJECT_ROOT_DIR}/gcc/gcc-arm-none-eabi-6-2017-q1-update/pkg` should not be empty, but rather the issues I found were in following commands (https://github.com/embedded-sec/uRAI/blob/master/compiler/setup_scripts/init_project.sh#L81-L83) where the version changed so these commands did not work.
> 
> Could you verify that you installed the pre-requisites, then pull the repository again and try the installation again. Hopefully it should work this time.
> 
> Thanks

Thanks for your response. Currently, I had installed pre-requisites and pulled the new repository. After running the "init_project.sh" script, it reported the following error:
~/workspace/uRAI/gcc/gcc-arm-none-eabi-6-2017-q1-update/src
mv: target '../../bins/' is not a directory
Should I build the 'bins' directory under '~/workspace/uRAI/gcc/' and copy the files under '~/workspace/uRAI/gcc/gcc-arm-none-eabi-6-2017-q1-update/pkg/gcc-arm-none-eabi-6-2021-q1-update' to '../../bins'?
